### ISSUE TITLE
3.1 Object Oriented Analysis

### ISSUE THREAD

**Issue by nevermyuk** [ICT2x01-P4-7/ICT2x01-P4-7-ICT2x01-p4-7#19]
- [x] Class Diagram 
- [x] Component Diagram
- [x] Sequence Diagram @TsukiBani @nevermyuk 
- [x] Communication Diagram@chuayingweidexter

**Comment by nevermyuk** [comment]
Meeting on 17 Oct.
Done class and component diagram as a group.
@gteckseng @TsukiBani @chuayingweidexter

**Comment by TsukiBani** [comment]
Met on 17 Oct to do class diagram I have a better understanding on how to separate entity, boundary, control

**Comment by nevermyuk** [comment]
@chuayingweidexter remember to format the diagrams and add into SRS

**Comment by nevermyuk** [comment]
> Communication Diagram
> 
> * [x]  UC-1
> * [x]  UC-2
> * [x]  UC-3
> * [x]  UC-4
> * [x]  UC-5
> * [x]  UC-6
> * [x]  UC-7
> * [x]  UC-8
> * [x]  UC-9
> * [x]  UC-10

Reviewed the communication diagrams, classes are correct, but the sequence numbering is wrong. Please take a look at it, created an example of UC2.

**Comment by chuayingweidexter** [comment]
> > Communication Diagram
> > 
> > * [x]   UC-1
> > * [x]   UC-2
> > * [x]   UC-3
> > * [x]   UC-4
> > * [x]   UC-5
> > * [x]   UC-6
> > * [x]   UC-7
> > * [x]   UC-8
> > * [x]   UC-9
> > * [x]   UC-10
> 
> Reviewed the communication diagrams, classes are correct, but the sequence numbering is wrong. Please take a look at it, created an example of UC2.

Corrected. Added into Document

**Comment by nevermyuk** [comment]
Updated all sequence diagrams. Made the respective changes to component diagrams too.
