### ISSUE TITLE
M1: 1.2.2 Functional Requirements

### ISSUE THREAD

**Issue by nevermyuk** [ICT2x01-P4-7/ICT2x01-P4-7-ICT2x01-p4-7#2]
Section 3: Specific Requirement

3.1.1 User interfaces @TsukiBani 
   Wireframe of the web portal UI interface

3.1.2 Hardware interfaces @nevermyuk 
   Identify the hardware interfaces and interactions

3.1.3 Software interfaces @nevermyuk 

3.2 Functional Requirements @retxedchua

**Comment by nevermyuk** [comment]
- Updated Section 3.1.2 'Hardware interfaces' to include MSP432 and the sensors provided, with a brief description.
- Updated Section 3.1.3 'Software interfaces' on how the software will interface with the robotic car.

**Comment by retxedchua** [comment]
Added Functional Requirements and Separated into two categories, Functional Requirements for web portal and Functional Requirements for the robotic car

**Comment by TsukiBani** [comment]
Create the wireframe for the user interface and edited the functional requirements
