### ISSUE TITLE
3.2 Software Architecture

### ISSUE THREAD

**Issue by nevermyuk** [ICT2x01-P4-7/ICT2x01-P4-7-ICT2x01-p4-7#20]

**Comment by nevermyuk** [comment]
@jevng Looking at the architecture. I think it should be more suited to be layered instead of MVC. Seems to be more aligned with how the application is going to be structured.

**Comment by jevng** [comment]
Hi @nevermyuk noted! I will review and update accordingly.

**Comment by jevng** [comment]
Updated to layered architecture and reviewed by team.

**Comment by nevermyuk** [comment]
lgtm.
