### ISSUE TITLE
History tab

### ISSUE THREAD

**Issue by gteckseng** [ICT2x01-P4-7/ICT2x01-P4-7-ICT2x01-p4-7#50]
History component in vue

**Comment by chuayingweidexter** [comment]
Added button + History Modal component to Program page

**Comment by chuayingweidexter** [comment]
Still require logic for populating History.

**Comment by nevermyuk** [comment]
Good attempt!  I know that there were some major blockers, will be taking over to implement.

**Comment by nevermyuk** [comment]
Completed.
