### ISSUE TITLE
Barred Log In Page

### ISSUE THREAD

**Issue by jevng** [ICT2x01-P4-7/ICT2x01-P4-7-ICT2x01-p4-7#51]
Page to restrict user log in for a limited period of time

**Comment by nevermyuk** [comment]
Added Backend logic to facilitate this process. It will return a JSON response with the time that will allow login attempts again.

{
    "message": "You have exceeded the max login attempts(5). Barred from logging in for the next 5 minutes.",
    "data": {
        "lockUntil": 1637677051646
    }
}

Make use of lockUntil(Epoch time) to determine countdown timer 👋

**Comment by nevermyuk** [comment]
Completed this.
